version: "3"
services:
  mysql8019:
    image: "mysql:8.0.19"
    ports:
      - "13306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /app/manifest/sql/create_table.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "simple_tiktok"
    volumes:
      - ./manifest/sql/create_table.sql:/app/manifest/sql/create_table.sql
  redis507:
    image: "redis:5.0.7"
    ports:
      - "16379:6379"
  app:
    build: .
    # command: "./wait-for.sh mysql8018:3306 redis507:6379 -- ./myapp"
    command: "./myapp"
    ports:
      - "8989:8989"
    depends_on:
      - mysql8019
      - redis507
